"use client";
import {useEffect,useRef,useState} from "react";
import {Scissors,ShieldCheck,Fingerprint,Network,Play,ArrowRight,ArrowUpRight,Check,Clock,FileCheck2,RotateCcw,Download,Terminal,ShieldAlert,LoaderCircle,Copy,X,UserRound,PackageCheck,Eye,GitBranch,ChevronRight,Pause} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {verifyEvidence} from "@/lib/evidence.mjs";
import {decode} from "@/lib/crypto.mjs";
type Data=any;
const attacks=[
["spoof","Identity spoof","Mirror signs as Relay."],["tamper","Tampered amount","Change the bytes after signing."],["replay","Replay request","Try to execute one order twice."],["escalation","Privilege escalation","Expand a child grant's scope."],["revocation-race","Revoke after approval","Cut authority between check and act."],["budget","Sibling overspend","Spend one budget through two agents."],["audience","Wrong recipient","Redirect a valid request."],["expired","Expired request","Present an expired signed request."],["vouch","Forged vouch","Impersonate the trusted auditor."],["chain","Chain substitution","Swap signed delegation chains."],["outage","Status outage","Lose live authority status."],["scope","Out-of-scope order","Exceed the delegated amount."]
];
const money=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(c/100);
const short=(s:string)=>s?s.slice(0,14)+"…"+s.slice(-6):"";
const steps=[
{title:"Let a trusted agent act.",text:"Relay orders $180 of supplies. Harbor verifies its identity, mandate, and supplier relationship before committing.",button:"Execute a valid order"},
{title:"Prepare the next request.",text:"Prepare another $180 order. This check passes, but it is not a promise of future authority.",button:"Prepare the next order"},
{title:"Now cut the authority.",text:"Northstar revokes Atlas's parent mandate. Relay and Scout immediately lose the authority derived from it.",button:"Cut parent authority"},
{title:"Try the verified request.",text:"The same signed request still proves Relay's identity. Its revoked mandate must prevent execution.",button:"Attempt execution"},
{title:"Make the proof portable.",text:"Verify the signed audit chain and Harbor's order acceptance. One order executed; the revoked request did not.",button:"Verify the evidence"}
];
export default function TrustLab(){
 const [state,setState]=useState<Data>(null),[busy,setBusy]=useState(""),[error,setError]=useState(""),[tab,setTab]=useState("live"),[amount,setAmount]=useState("180");
 const [selected,setSelected]=useState<Data>(null),[results,setResults]=useState<Record<string,Data>>({}),[trial,setTrial]=useState<Data>(null);
 const [bundle,setBundle]=useState<Data>(null),[proof,setProof]=useState<Data>(null),[pasted,setPasted]=useState(""),[copied,setCopied]=useState(false);
 const [guide,setGuide]=useState(-1),[notice,setNotice]=useState("");const init=useRef(false);
 async function call(op:string,extra:Data={}){
  setError("");setBusy(op);
  try{const r=await fetch("/api/lab",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({op,requestId:state?.pending?.requestId,...extra})});const d:Data=await r.json();if(!r.ok)throw Error(d.error);if(d.state)setState(d.state);return d;}catch(e){setError(e instanceof Error?e.message:"Connection unavailable");return null;}finally{setBusy("");}
 }
 useEffect(()=>{if(!init.current){init.current=true;void call("connect");}},[]);
 const cut=state?.revoked.includes(state?.rootMandate),decision=state?.lastDecision,actors=state?.actors||[];
 async function run(id:string){const d=await call("attack",{attack:id});if(d){setResults(x=>({...x,[id]:d.attack}));setTrial(d.attack);}}
 async function allAttacks(){setError("");setBusy("suite");try{for(const [id] of attacks){const r=await fetch("/api/lab",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({op:"attack",attack:id})});const d:Data=await r.json();if(!r.ok)throw Error(d.error);setResults(x=>({...x,[id]:d.attack}));setTrial(d.attack);}}catch(e){setError(e instanceof Error?e.message:"Trial unavailable");}finally{setBusy("");}}
 async function verifyBundle(data?:Data){setBusy("verify");setError("");try{let b=data;if(!b){const r=await fetch("/api/lab?export=evidence");if(!r.ok)throw Error("Could not load evidence");b=await r.json();}const root=actors.find((a:Data)=>a.alias==="principal")?.did,auditor=actors.find((a:Data)=>a.alias==="auditor")?.did;setBundle(b);setProof(await verifyEvidence(b,root,auditor));}catch(e){setError(e instanceof Error?e.message:"Invalid evidence");}finally{setBusy("");}}
 async function startGuide(){const d=await call("reset");if(d){setGuide(0);setTab("live");setProof(null);setNotice("");}}
 async function nextStep(){
  let d;
  if(guide===0){d=await call("prepare",{amountCents:18000});if(d)d=await call("execute",{requestId:d.state.pending.requestId});}
  if(guide===1)d=await call("prepare",{amountCents:18000});
  if(guide===2)d=await call("revoke");
  if(guide===3)d=await call("execute");
  if(guide===4){setTab("evidence");await verifyBundle();setGuide(5);return;}
  if(d)setGuide(x=>x+1);
 }
 function download(){if(!bundle)return;const u=URL.createObjectURL(new Blob([JSON.stringify(bundle,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=u;a.download="trustcut-evidence.json";a.click();URL.revokeObjectURL(u);}
 async function copy(){try{await navigator.clipboard.writeText(JSON.stringify(selected?.payload||selected,null,2));setCopied(true);}catch{setNotice("Select the displayed JSON to copy it.");}}
 function profile(a:Data){setCopied(false);setSelected({title:a.name+" · "+a.role,payload:{did:a.did,identity:decode(a.credential),authority:a.alias==="relay"||a.alias==="scout"?state.chains[a.alias].map(decode):a.alias==="atlas"?[decode(state.chains.relay[0])]:[],history:state.events.filter((e:Data)=>e.actor===a.did),attestations:a.alias==="harbor"?[decode(state.vouch)]:[]}});}
 const positions:Record<string,[number,number]>={principal:[13,45],atlas:[38,45],relay:[64,21],scout:[64,73],harbor:[89,45]};
 const NodeIcon:Record<string,any>={principal:UserRound,atlas:GitBranch,relay:Fingerprint,scout:Fingerprint,harbor:PackageCheck};
 return <main className="lab-shell">
 <header className="topbar"><a href="/" className="brand"><span className="brand-mark"><Scissors size={23}/></span>trustcut<span>.</span></a><span className="top-label">AGENT AUTHORITY LAB</span><div className="top-right"><span className="sandbox-tag">Isolated sandbox</span><a href="/brief" className="brief-link">Technical brief <ArrowUpRight size={15}/></a></div></header>
 <div className="workspace-heading"><div><p className="eyebrow">IDENTITY IS PROVEN. AUTHORITY IS CONDITIONAL.</p><h1>Know when trust <em>ends.</em></h1></div><Button onClick={startGuide} disabled={!!busy||!state} className="guide-start"><Play size={16}/> Run the 90-second story</Button></div>
 {error&&<div role="alert" className="error-banner"><span>{error}</span><Button variant="outline" onClick={()=>call("connect")}>Reconnect</Button></div>}
 {notice&&<p className="notice" role="status">{notice}</p>}
 <Tabs value={tab} onValueChange={setTab}>
 <div className="workspace-nav"><TabsList variant="line"><TabsTrigger value="live"><Network/> Live network</TabsTrigger><TabsTrigger value="attacks"><ShieldAlert/> Attack lab</TabsTrigger><TabsTrigger value="evidence"><FileCheck2/> Evidence</TabsTrigger></TabsList><span className="meta">Ed25519 <span className="separator">/</span> did:key <span className="separator">/</span> VC 2.0 profile</span></div>
 <TabsContent value="live">
 <div className="lab-grid"><section className="network-panel"><div className="panel-heading"><h2>Delegated authority</h2><span className={"state-label "+(cut?"denied":"allowed")}>{cut?"PARENT REVOKED":"ACTIVE MANDATE"}</span></div>
 <div className={"trust-graph "+(cut?"is-cut":"")}>
 <svg viewBox="0 0 1000 380" preserveAspectRatio="none" className="edges" aria-hidden="true"><path className="grant-edge root-edge" d="M130 171H380"/><path className="grant-edge" d="M380 171C495 171 525 80 640 80"/><path className="grant-edge" d="M380 171C495 171 525 277 640 277"/><path className="exchange-edge" d="M640 80C770 80 760 171 890 171"/><path className="exchange-edge" d="M640 277C770 277 760 171 890 171"/></svg>
 <span className="edge-label root-label">{cut?"REVOKED":"$600 shared budget"}</span><span className="edge-label buyer-label">$300 / order</span><span className="edge-label exchange-label">verify + accept</span>
 {actors.filter((a:Data)=>positions[a.alias]).map((a:Data)=>{const [x,y]=positions[a.alias],Icon=NodeIcon[a.alias];return <button key={a.alias} className={"graph-node node-"+a.alias+((cut&&["atlas","relay","scout"].includes(a.alias))?" revoked":"")} style={{left:x+"%",top:y+"%"}} onClick={()=>profile(a)} aria-label={"Inspect "+a.name+" trust profile"}><span className="node-icon"><Icon size={23}/></span><strong>{a.name}</strong><span>{a.role}</span><small>{cut&&["atlas","relay","scout"].includes(a.alias)?"Authority cut":"Signed identity"}</small></button>;})}
 </div>
 <div className="mobile-chain">{actors.filter((a:Data)=>positions[a.alias]).map((a:Data)=><button key={a.alias} onClick={()=>profile(a)}><Fingerprint size={20}/><span><strong>{a.name}</strong><small>{a.role}</small></span><span className="meta">{cut&&["atlas","relay","scout"].includes(a.alias)?"Revoked":"Signed"}</span><ChevronRight size={17}/></button>)}</div>
 <div className="witness-row"><span className="witness-icon"><Eye size={18}/></span><span><strong>Witness</strong> <span>signs the audit trail and vouches for Harbor.</span></span><button aria-label="Inspect Witness trust profile" onClick={()=>profile(actors.find((a:Data)=>a.alias==="auditor"))}><ArrowUpRight size={18}/></button></div>
 <div className="budget-row"><div><p className="eyebrow">ONE BUDGET. TWO BUYERS.</p><strong>{money(state?.budgetCents-(state?.spentCents||0)||0)} <span>remaining</span></strong></div><div className="budget-meter"><div><span>Committed {money(state?.spentCents||0)}</span><span>$600</span></div><div className="meter-track"><div style={{width:((state?.spentCents||0)/600)+"%"}}/></div></div></div>
 </section>
 <section className={"decision-panel "+(decision?.verdict||"ready").toLowerCase()} aria-live="polite"><div className="decision-eyebrow"><ShieldCheck size={18}/><p className="eyebrow">HARBOR'S DECISION</p></div><h2 className="verdict">{busy&&!state?"CONNECTING":decision?.verdict||"READY"}</h2><p className="decision-reason">{decision?.reason||"Prepare a stock order. Inspect the proof before you let the agent act."}</p>
 <div className="order-input"><label htmlFor="amount">Order amount · USD</label><div><span>$</span><Input id="amount" type="number" min="1" max="1000000" step="1" value={amount} onChange={e=>setAmount(e.target.value)} disabled={!!busy}/></div><small>Relay's limit $300 · Auto-approve ≤ $200</small></div>
 <div className="action-stack"><Button onClick={()=>call("prepare",{amountCents:Math.round(Number(amount)*100)})} disabled={!!busy||!state||!amount||Number(amount)<=0}><Fingerprint/> Prepare & verify <ArrowRight/></Button>
 <Button variant="secondary" onClick={()=>call("execute")} disabled={!!busy||!state?.pending}><PackageCheck/> Execute prepared order</Button>
 {state?.pending&&decision?.code==="APPROVAL_REQUIRED"&&<Button variant="outline" onClick={()=>call("approve")} disabled={!!busy}><UserRound/> Sign exact-order approval</Button>}
 <Button variant="outline" className="cut-button" disabled={!!busy||!state||cut} onClick={()=>call("revoke")}><Scissors/> {cut?"Parent authority revoked":"Cut parent authority"}</Button></div>
 <p className="pending-hint"><Clock size={14}/>{state?.pending?"Prepared request expires in two minutes.":"Preparation does not execute an order."}</p>
 </section></div>
 <div className="detail-grid"><section className="checks-panel"><div className="panel-heading"><h2>Decision trace</h2><span className="meta">{decision?.checks?.length||0} checks</span></div><Trace decision={decision}/></section><section className="history-panel"><div className="panel-heading"><h2>Execution ledger</h2><span className="meta">{state?.ledger?.length||0} orders</span></div>{state?.ledger?.length?state.ledger.slice().reverse().map((o:Data)=><button className="ledger-row" key={o.id} onClick={()=>setSelected({title:"Signed supplier acceptance",payload:decode(o.acceptance)})}><span className="ledger-icon"><PackageCheck size={19}/></span><span><strong>{money(o.amountCents)} stock order</strong><small>Harbor accepted · {o.requestId.slice(0,8)}</small></span><FileCheck2 size={18}/></button>):<div className="empty"><PackageCheck/><p>No orders executed.</p><small>An ALLOW check alone adds nothing here.</small></div>}<div className="ledger-note">An order appears only after authority, nonce, and budget commit together.</div></section></div>
 </TabsContent>
 <TabsContent value="attacks"><section className="attack-intro"><div><p className="eyebrow">TRY TO BREAK THE TRUST MODEL</p><h2>Valid identity. Invalid authority.</h2><p>Each attack generates fresh keys and signed evidence in an isolated trial. The main ledger stays intact.</p></div><Button onClick={allAttacks} disabled={!!busy||!state}>{busy==="suite"?<LoaderCircle className="spin"/>:<Play/>}Run all 12 attacks</Button></section>
 <div className="attack-layout"><div className="attack-grid">{attacks.map(([id,name,detail],index)=><button className={"attack-card "+(trial?.id===id?"selected":"")} key={id} disabled={!!busy||!state} onClick={()=>run(id)}><div><span className="meta">{String(index+1).padStart(2,"0")}</span>{results[id]?<span className={results[id].passed?"allowed":"denied"}>{results[id].passed?<Check size={18}/>:<X size={18}/>}</span>:<ArrowUpRight size={17}/>}</div><strong>{name}</strong><p>{detail}</p><span className="attack-verdict">{results[id]?.decision.verdict||"Run trial"}</span></button>)}</div>
 <section className="trial-panel"><div className="panel-heading"><h2>Failure proof</h2><span className="meta">{Object.values(results).filter((r:Data)=>r.passed).length}/12 verified</span></div>{trial?<><div className="trial-result"><p className={"state-label "+(trial.decision.verdict==="DENY"?"denied":"escalated")}>{trial.decision.verdict}</p><h3>{trial.decision.code}</h3><p>{trial.decision.reason}</p><div className="effect-proof"><Check size={18}/>{trial.passed?"Expected defense verified":"Unexpected result"}<small>Orders before {trial.ordersBefore} → after {trial.ordersAfter}</small></div></div><Trace decision={trial.decision}/></>:<div className="empty"><ShieldAlert/><p>Select an attack.</p><small>Inspect the failed rule and absence of new execution.</small></div>}</section></div></TabsContent>
 <TabsContent value="evidence"><section className="evidence-intro"><div><p className="eyebrow">PROOF YOU CAN TAKE WITH YOU</p><h2>Don't trust the dashboard.<br/>Verify the signatures.</h2><p>Verify against this sandbox's pinned root and auditor keys. Export contains public evidence only.</p></div><div className="evidence-actions"><Button onClick={()=>verifyBundle()} disabled={!!busy||!state}><FileCheck2/> Verify current evidence</Button><Button variant="outline" onClick={download} disabled={!bundle}><Download/> Download evidence</Button></div></section>
 {proof&&<div className={"verification-result "+(proof.valid?"good":"bad")} role="status">{proof.valid?<ShieldCheck size={32}/>:<ShieldAlert size={32}/>}<div><h3>{proof.valid?"VERIFIED":"VERIFICATION FAILED"}</h3><p>{proof.reason}</p>{proof.valid&&<span>{proof.receipts} receipts · {proof.credentials} credentials · {proof.orders} signed acceptances</span>}</div></div>}
 <div className="evidence-grid"><section className="history-panel"><div className="panel-heading"><h2>Signed audit trail</h2><span className="meta">SHA-256 linked</span></div>{state?.events?.length?state.events.slice().reverse().map((e:Data)=><button key={e.id} className="audit-row" onClick={()=>setSelected({title:e.kind+" · signed receipt",payload:{...decode(e.token),JWS:e.token}})}><span className={"audit-status "+e.verdict.toLowerCase()}>{e.verdict==="ALLOW"?<Check size={15}/>:e.verdict==="DENY"?<X size={15}/>:<Pause size={15}/>}</span><span><strong>{e.kind.replaceAll("_"," ")}</strong><small>{e.reason}</small><code>{short(e.hash)}</code></span><ArrowUpRight size={16}/></button>):<div className="empty"><FileCheck2/><p>Run an interaction to produce receipts.</p></div>}</section><section className="proof-details"><h3>What this proves</h3><p>Who signed, whether the evidence changed, the complete checkpointed audit chain, and Harbor's signed sandbox acceptance.</p><h3>What this does not prove</h3><p>External delivery, agent intent, current future authority, or independent key custody. The scripted agents share one sandbox operator.</p><label htmlFor="bundle">Check an exported bundle</label><Textarea id="bundle" rows={5} value={pasted} onChange={e=>setPasted(e.target.value)} placeholder="Paste evidence JSON to verify or tamper-test it…"/><Button variant="outline" disabled={!!busy||!pasted||!state} onClick={()=>{try{void verifyBundle(JSON.parse(pasted));}catch{setError("Enter valid JSON.");}}}><Terminal/> Verify pasted evidence</Button><p className="meta">Offline verifier: scripts/verify-evidence.mjs<br/>Pin trusted DIDs separately from the bundle.</p></section></div></TabsContent>
 </Tabs>
 {guide>=0&&<section className="guide-bar" aria-live="polite"><div className="guide-count">{guide<5?String(guide+1).padStart(2,"0"):<Check/>}<small>/ 05</small></div><div><p className="eyebrow">THE 90-SECOND STORY</p><h3>{guide<5?steps[guide].title:"Identity stayed valid. Authority ended."}</h3><p>{guide<5?steps[guide].text:"The first order executed. The revoked request did not. The evidence is independently checkable."}</p></div>{guide<5?<Button disabled={!!busy} onClick={nextStep}>{steps[guide].button}<ArrowRight/></Button>:<Button variant="outline" onClick={()=>setGuide(-1)}>Explore the lab</Button>}<button aria-label="Close guided story" onClick={()=>setGuide(-1)}><X size={18}/></button></section>}
 <footer className="app-footer"><span>{busy?<LoaderCircle size={15} className="spin"/>:<ShieldCheck size={15}/>}Real signatures. Scripted agents. Sandbox orders.</span><div><Button variant="ghost" disabled={!!busy||!state} onClick={()=>call(state.suspended?"resume-status":"pause-status")}>{state?.suspended?"Restore status":"Simulate status outage"}</Button><Button variant="ghost" disabled={!!busy||!state} onClick={async()=>{const d=await call("reset");if(d){setGuide(-1);setProof(null);setBundle(null);}}}><RotateCcw/>Reset sandbox</Button></div></footer>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="proof-dialog"><DialogHeader><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>Public, signed evidence. Private signing keys stay on the sandbox server.</DialogDescription></DialogHeader><pre>{JSON.stringify(selected?.payload,null,2)}</pre><Button variant="outline" onClick={copy}><Copy/>{copied?"Copied":"Copy JSON"}</Button></DialogContent></Dialog>
 </main>;
}
function Trace({decision}:{decision:Data}){return decision?.checks?.length?<ol className="trace-list">{decision.checks.map((c:Data)=><li key={c.code} className={c.status}><span className="trace-icon">{c.status==="pass"?<Check size={14}/>:c.status==="hold"?<Pause size={14}/>:<X size={14}/>}</span><div><strong>{c.label}</strong><p>{c.detail}</p></div></li>)}{decision.repair&&<li className="repair"><span><ArrowRight size={17}/></span><div><strong>Required next step</strong><p>{decision.repair}</p></div></li>}</ol>:<div className="empty"><Fingerprint/><p>The proof will appear here.</p><small>Prepare an order to evaluate its signed authority.</small></div>;}
