
const enc=new TextEncoder(),dec=new TextDecoder("utf-8",{fatal:true}),alphabet="123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
export function canonical(x){if(x===null||typeof x==="string"||typeof x==="boolean")return JSON.stringify(x);if(typeof x==="number"&&Number.isFinite(x))return JSON.stringify(x);if(Array.isArray(x))return "["+x.map(canonical).join(",")+"]";if(x&&Object.getPrototypeOf(x)===Object.prototype)return "{"+Object.keys(x).sort().map(k=>JSON.stringify(k)+":"+canonical(x[k])).join(",")+"}";throw Error("Unsupported JSON");}
export const b64=x=>btoa(String.fromCharCode(...x)).replace(/=/g,"").replace(/\+/g,"-").replace(/\//g,"_");
export function unb64(s){if(typeof s!=="string"||!s||!/^[\w-]+$/.test(s))throw Error("Malformed encoding");return Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/")),c=>c.charCodeAt(0));}
export async function hash(x){const bytes=enc.encode(typeof x==="string"?x:canonical(x));if(globalThis.crypto?.subtle)return b64(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes)));const {sha256}=await import("@noble/hashes/sha2.js");return b64(sha256(bytes));}
function base58(bytes){let n=0n,out="";for(const b of bytes)n=n*256n+BigInt(b);while(n){out=alphabet[Number(n%58n)]+out;n/=58n;}for(const b of bytes){if(b)break;out="1"+out;}return out;}
function from58(s){if(!s||s.length>64)throw Error("Bad DID");let n=0n;const out=[];for(const c of s){const i=alphabet.indexOf(c);if(i<0)throw Error("Bad DID");n=n*58n+BigInt(i);}while(n){out.unshift(Number(n%256n));n/=256n;}for(const c of s){if(c!=="1")break;out.unshift(0);}return new Uint8Array(out);}
export function didFromKey(jwk){if(jwk.kty!=="OKP"||jwk.crv!=="Ed25519")throw Error("Wrong key type");const bytes=unb64(jwk.x);if(bytes.length!==32)throw Error("Wrong key length");return "did:key:z"+base58(new Uint8Array([0xed,1,...bytes]));}
export function keyFromDid(did){if(typeof did!=="string"||!did.startsWith("did:key:z"))throw Error("Unsupported DID");const b=from58(did.slice(9));if(b.length!==34||b[0]!==0xed||b[1]!==1)throw Error("Invalid Ed25519 DID");return {kty:"OKP",crv:"Ed25519",x:b64(b.slice(2))};}
export async function identity(){const k=await crypto.subtle.generateKey("Ed25519",true,["sign","verify"]);const pub=await crypto.subtle.exportKey("jwk",k.publicKey);return {did:didFromKey(pub),publicJwk:pub,privateJwk:await crypto.subtle.exportKey("jwk",k.privateKey)};}
export async function sign(data,key,typ="trustcut+jwt"){const h=b64(enc.encode(canonical({alg:"EdDSA",kid:key.did+"#"+key.did.slice(8),typ})));const p=b64(enc.encode(canonical(data)));const k=await crypto.subtle.importKey("jwk",key.privateJwk,"Ed25519",false,["sign"]);return h+"."+p+"."+b64(new Uint8Array(await crypto.subtle.sign("Ed25519",k,enc.encode(h+"."+p))));}
export function decode(token){if(typeof token!=="string"||token.length>30000||token.split(".").length!==3)throw Error("Malformed JWS");return JSON.parse(dec.decode(unb64(token.split(".")[1])));}
export async function verify(token,did,typ="trustcut+jwt"){decode(token);const [h,p,s]=token.split(".");const header=JSON.parse(dec.decode(unb64(h)));if(canonical(header)!==canonical({alg:"EdDSA",kid:did+"#"+did.slice(8),typ}))throw Error("Untrusted signature header");const jwk=keyFromDid(did),sig=unb64(s),message=enc.encode(h+"."+p);if(sig.length!==64)throw Error("Signature mismatch");let valid;if(globalThis.crypto?.subtle){const k=await crypto.subtle.importKey("jwk",jwk,"Ed25519",false,["verify"]);valid=await crypto.subtle.verify("Ed25519",k,sig,message);}else{const {ed25519}=await import("@noble/curves/ed25519.js");valid=ed25519.verify(sig,message,unb64(jwk.x),{zip215:false});}if(!valid)throw Error("Signature mismatch");return decode(token);}
export function tamper(token,change){const p=token.split("."),d=decode(token);change(d);p[1]=b64(enc.encode(canonical(d)));return p.join(".");}
